---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400
  changed_when: false

# Add specified repository into sources list using specified filename.
- name: Add an Apt signing key to a specific keyring file
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    keyring: /etc/apt/trusted.gpg.d/php.gpg

- name: Add PHP repo in Debian
  apt_repository:
    repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
    state: present
    filename: php7
