---
# - build docker containers
- name: Build Docker images from Dockerfile.
  docker_image:
    name: "{{ item.image_name }}"
    tag: "{{ item.tag }}"
    source: build
    build:
      path: "{{ item.directory }}"
      pull: false
    state: present
  with_items: "{{ deploy_list }}"

# - deploy docker containers
- name: Build "{{ item.container_name }}" container.
  docker_container:
    image: "{{ item.image_name }}"
    name: "{{ item.container_name }}"
    links:
      - "{{ item.link_db }}:db"
    ports: "{{ item.ports }}"
    state: "{{ item.state }}"
  with_items: "{{ deploy_list }}"