---
- hosts: develop
  become: yes
  become_method: sudo
  vars:
    - user: "{{ ansible_user }}"

  pre_tasks:
    - name: "Provision [{{ ansible_distribution }}] with Ansible"
      debug:
        msg: Set up host [{{ inventory_hostname }}::{{ ansible_host }}] with user [{{ ansible_user }}]

    - name: Update apt cache if needed
      apt: update_cache=yes cache_valid_time=3600

  roles:
    - role: bootstrap
      time_zone: 'Canada/Pacific'

    - role: python3

    - role: php
      php_ver: '7.4'
    - role: nginx
      php_ver: '7.4'

    - role: docker
      docker_group_members: ["{{ user }}"]

    # https://github.com/morgangraphics/ansible-role-nvm
    # fixed /etc/bash => /bin/bash
    - role: ansible-role-nvm
      nodejs_version: "12.16.3"
      nvm_commands:
       - "nvm exec default npm install"
      become_user: "{{ user }}"

  tasks:
    - import_tasks: develop-dockers.yml
      vars:
        - data: {name: data}
        - db: {name: mysql, version: 8.0, root_password: root, database: dev, user: dev, password: dev, port: 3306}
        - dbadmin: {name: phpmyadmin, port: 8081}
        - redis: {name: redis, port: 6379}
      become: yes
      become_method: sudo
