---
# build docker containers

# Data container
- name: Create a data container
  docker_container:
    image: busybox
    name: mydata
    volumes:
      - /var/data
    state: present

# MySQL container
# docker run --name mysql_db -e MYSQL_ROOT_PASSWORD=dev -d mysql:5.7
- name: Create a MySQL container.
  docker_container:
    image: mysql:5.7
    name: mysql_db
    volumes_from: mydata
    ports: 3306:3306
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      MYSQL_DATABASE: "{{ mysql_databases }}"
      MYSQL_USER: "{{ mysql_user }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
    state: started

# Redis container
# docker run --name myredis -d redis redis-server --appendonly yes --volumes_from mydata
- name: Create a redis container
  docker_container:
    image: redis
    name: myredis
    volumes_from: mydata
    ports: 6379:6379
    command: redis-server --appendonly yes
    state: started
    recreate: yes

# phpMyAdmin
# docker run --name myadmin -d --link mysql_db:db -p 8080:80 phpmyadmin/phpmyadmin
- name: Create a phpMyAdmin container
  docker_container:
    image: phpmyadmin/phpmyadmin:latest
    name: myadmin
    links:
      - mysql_db:db
    ports: 8080:80
    state: started