---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400
  changed_when: false

- name: Install nginx
  apt:
    name: nginx
    state: present
  notify: restart nginx

- name: create self-signed SSL cert
  command: openssl req -nodes -x509 -newkey rsa:4096 -keyout /etc/nginx/cert.key -out /etc/nginx/cert.crt -days 356 -subj "/C=CA/ST=BC/L=Vancouver/O=AP/CN=vagrant-dev-server"
  notify: restart nginx

# nginx default configuration.
- name: Remove default nginx host config file.
  file:
    path: "{{ nginx_default_vhost_conf }}"
    state: absent
  when: nginx_remove_default_vhost
  notify: restart nginx

- name: Remove default nginx host folder.
  file:
    path: "{{ nginx_default_vhost_folder }}"
    state: absent
  when: nginx_remove_default_vhost
  notify: restart nginx

# nginx virtual hosts configuration.
- name: Ensure nginx_vhost_folder exists.
  file:
    path: "{{ nginx_vhost_folder }}"
    state: directory
  notify: restart nginx

- name: Remove host config files.
  file:
    path: "{{ nginx_vhost_folder }}/{{ item.filename|default(item.server_name.split(' ')[0] ~ '.conf') }}"
    state: absent
  when: item.state|default('present') == 'absent'
  with_items: "{{ nginx_vhost_list }}"
  notify: restart nginx

- name: Add host config files.
  template:
    src: "{{ item.template|default(nginx_vhost_template) }}"
    dest: "{{ nginx_vhost_folder }}/{{ item.filename|default(item.server_name.split(' ')[0] ~ '.conf') }}"
    force: yes
    mode: 0644
  when: item.state|default('present') != 'absent'
  with_items: "{{ nginx_vhost_list }}"
  notify: restart nginx