---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400
  changed_when: false

- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Generate OpenSSL private key
  openssl_privatekey: path=/etc/nginx/nginx.key

- name: Generate OpenSSL Certificate Signing Request
  openssl_csr: path=/etc/nginx/csr.csr  privatekey_path=/etc/nginx/nginx.key common_name=test.web

- name: Generate Self-signed certificate
  openssl_certificate: path=/etc/nginx/nginx.crt privatekey_path=/etc/nginx/nginx.key csr_path=/etc/nginx/csr.csr provider=selfsigned
  notify: restart nginx

# nginx default configuration.
- name: Remove default nginx host config file.
  file:
    path: "{{ nginx_default_vhost_conf }}"
    state: absent
  when: nginx_remove_default_vhost
  notify: restart nginx

- name: Remove default nginx host folder.
  file:
    path: "{{ nginx_default_vhost_folder }}"
    state: absent
  when: nginx_remove_default_vhost
  notify: restart nginx

# nginx virtual hosts configuration.
- name: Ensure nginx_vhost_conf_folder exists.
  file:
    path: "{{ nginx_vhost_conf_folder }}"
    state: directory
  notify: restart nginx

- name: Remove host config files.
  file:
    path: "{{ nginx_vhost_conf_folder }}/{{ item.conf | default(item.domain ~ '.conf') }}"
    state: absent
  when: item.state|default('present') == 'absent'
  with_items: "{{ nginx_vhost_list }}"
  notify: restart nginx

- name: Add host config files.
  template:
    src: "{{ item.template }}"
    dest: "{{ nginx_vhost_conf_folder }}/{{ item.conf | default(item.domain ~ '.conf') }}"
    force: yes
    mode: 0644
  when: item.state|default('present') != 'absent'
  with_items: "{{ nginx_vhost_list }}"
  notify: restart nginx

- name: Start nginx
  service:
      name: nginx
      state: started
      enabled: yes